# Generated by Django 4.1.2 on 2022-12-14 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="profile_pic",
            field=models.ImageField(
                default="default_person.jpg", upload_to="profile_pics"
            ),
        ),
    ]
