# Generated by Django 4.1.2 on 2022-12-20 14:38

import ckeditor.fields
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                ("cid", models.AutoField(primary_key=True, serialize=False)),
                ("category_name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                ("commentid", models.AutoField(primary_key=True, serialize=False)),
                ("comment", models.TextField()),
                ("created", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Post",
            fields=[
                ("aid", models.AutoField(primary_key=True, serialize=False)),
                (
                    "image",
                    models.ImageField(default="blog-default.png", upload_to="images/"),
                ),
                ("title", models.CharField(max_length=200)),
                ("content", ckeditor.fields.RichTextField()),
                ("created", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "approved",
                    models.BooleanField(default=False, verbose_name="Approved"),
                ),
            ],
        ),
    ]
