# Generated by Django 4.1.2 on 2022-11-30 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                ("cid", models.AutoField(primary_key=True, serialize=False)),
                ("category_name", models.CharField(max_length=100)),
            ],
        ),
    ]
