# Generated by Django 4.1.2 on 2022-12-11 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_post"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="image",
            field=models.ImageField(
                blank=True, default="blog-default.png", null=True, upload_to="images/"
            ),
        ),
    ]
