# Generated by Django 4.1.2 on 2022-12-12 21:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_post_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="cid",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="blog.category",
                verbose_name="specialization",
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="image",
            field=models.ImageField(default="blog-default.png", upload_to="images/"),
        ),
    ]
