# Generated by Django 4.1.2 on 2022-12-12 22:46

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0004_alter_post_cid_alter_post_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post", name="content", field=ckeditor.fields.RichTextField(),
        ),
    ]
