# Generated by Django 4.1.2 on 2022-12-13 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0005_alter_post_content"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="approved",
            field=models.BooleanField(default=False, verbose_name="Approved"),
        ),
    ]
